name: 'Close cards moved to Done Lane'

on:
  project_card:
    types: [created, edited, moved]

permissions:
  repository-projects: read
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/issue-states@v3
        with:
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          open-issue-columns: ''
          closed-issue-columns: 'Done'
          log-output: false